# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statclustmaket.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 379)
        self.clusterRunButtons = QtWidgets.QDialogButtonBox(Dialog)
        self.clusterRunButtons.setGeometry(QtCore.QRect(320, 330, 161, 32))
        self.clusterRunButtons.setOrientation(QtCore.Qt.Horizontal)
        self.clusterRunButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.clusterRunButtons.setObjectName("clusterRunButtons")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 491, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLay = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLay.setContentsMargins(0, 0, 0, 0)
        self.mainLay.setObjectName("mainLay")
        self.leftLay = QtWidgets.QVBoxLayout()
        self.leftLay.setContentsMargins(10, 10, 10, 10)
        self.leftLay.setSpacing(10)
        self.leftLay.setObjectName("leftLay")
        self.criterionLayout = QtWidgets.QVBoxLayout()
        self.criterionLayout.setSpacing(10)
        self.criterionLayout.setObjectName("criterionLayout")
        self.criterionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.criterionLabel.setObjectName("criterionLabel")
        self.criterionLayout.addWidget(self.criterionLabel)
        self.criterionBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.criterionBox.setObjectName("criterionBox")
        self.criterionLayout.addWidget(self.criterionBox)
        self.leftLay.addLayout(self.criterionLayout)
        self.methodLayout = QtWidgets.QVBoxLayout()
        self.methodLayout.setSpacing(10)
        self.methodLayout.setObjectName("methodLayout")
        self.methodLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.methodLabel.setObjectName("methodLabel")
        self.methodLayout.addWidget(self.methodLabel)
        self.methodBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.methodBox.setObjectName("methodBox")
        self.methodLayout.addWidget(self.methodBox)
        self.leftLay.addLayout(self.methodLayout)
        self.metricLayout = QtWidgets.QVBoxLayout()
        self.metricLayout.setSpacing(10)
        self.metricLayout.setObjectName("metricLayout")
        self.metricLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.metricLabel.setObjectName("metricLabel")
        self.metricLayout.addWidget(self.metricLabel)
        self.metricBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.metricBox.setObjectName("metricBox")
        self.metricLayout.addWidget(self.metricBox)
        self.leftLay.addLayout(self.metricLayout)
        self.mainLay.addLayout(self.leftLay)
        self.rightLay = QtWidgets.QVBoxLayout()
        self.rightLay.setContentsMargins(10, 10, 10, 10)
        self.rightLay.setSpacing(10)
        self.rightLay.setObjectName("rightLay")
        self.nOfClustersLayout = QtWidgets.QVBoxLayout()
        self.nOfClustersLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.nOfClustersLayout.setContentsMargins(10, 10, 10, 10)
        self.nOfClustersLayout.setSpacing(10)
        self.nOfClustersLayout.setObjectName("nOfClustersLayout")
        self.nOfClustersLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nOfClustersLabel.setObjectName("nOfClustersLabel")
        self.nOfClustersLayout.addWidget(self.nOfClustersLabel)
        self.nOfClustersBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.nOfClustersBox.setObjectName("nOfClustersBox")
        self.nOfClustersLayout.addWidget(self.nOfClustersBox)
        self.rightLay.addLayout(self.nOfClustersLayout)
        self.columnsToClustLayout = QtWidgets.QVBoxLayout()
        self.columnsToClustLayout.setObjectName("columnsToClustLayout")
        self.columnsToClustLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.columnsToClustLabel.setObjectName("columnsToClustLabel")
        self.columnsToClustLayout.addWidget(self.columnsToClustLabel)
        self.columnsToClustList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnsToClustList.sizePolicy().hasHeightForWidth())
        self.columnsToClustList.setSizePolicy(sizePolicy)
        self.columnsToClustList.setObjectName("columnsToClustList")
        self.columnsToClustLayout.addWidget(self.columnsToClustList)
        self.rightLay.addLayout(self.columnsToClustLayout)
        self.mainLay.addLayout(self.rightLay)

        self.retranslateUi(Dialog)
        self.clusterRunButtons.accepted.connect(Dialog.accept)
        self.clusterRunButtons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.criterionLabel.setText(_translate("Dialog", "Критерий кластеризации"))
        self.methodLabel.setText(_translate("Dialog", "Метод кластеризации"))
        self.metricLabel.setText(_translate("Dialog", "Метрика кластеризации"))
        self.nOfClustersLabel.setText(_translate("Dialog", "Число кластеров"))
        self.columnsToClustLabel.setText(_translate("Dialog", "Столбцы для кластеризации"))


